# Generated by Django 4.2.7 on 2023-11-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0005_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantform",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
