# Generated by Django 4.2.7 on 2023-11-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0007_alter_tenantform_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantform",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=200,
                null=True,
            ),
        ),
    ]
