# Generated by Django 4.2.7 on 2023-11-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0012_alter_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="houseapplication",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="legalservice",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
