# Generated by Django 4.2.7 on 2023-12-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0015_tenantform_employer_tenantform_employer_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
