# Generated by Django 4.2.7 on 2024-01-03 12:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0017_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
