# Generated by Django 4.2.7 on 2024-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refxpert", "0018_alter_job_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_open",
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Open", "Open"), ("Closed", "Closed")],
                max_length=200,
                null=True,
            ),
        ),
    ]
